### ISSUE TITLE
'Total Force' Scalar displays sum of velocity differences instead of forces (Burgers' Equation)

### ISSUE THREAD

**Issue by Sh0cktr4p** [holl-/PDE-Control#1]
More of a minor detail, but I think in the total_force_loss method of the BurgersPDE class, self.scalars['Total Force'] should be set to l1 / self.dt instead of just l1. This way, the values are independent of the time step size and comparable to the values of the FieldEffect used to generate the ground truth.

**Comment by p-holl** [comment]
You're correct. However, since `dt` is just a constant in these experiments, it wouldn't affect the training or results.
