### ISSUE TITLE
About how to generate data in legacy code shape transition

### ISSUE THREAD

**Issue by kuwt** [holl-/PDE-Control#2]
I am currently trying to study the shape transition experiment from the legacy code so I need to generate the data using shapegen.py. However, I do not know how to produce the shapelib. I would like to know if I have misunderstood anything or if i can find the shapelib in some place or generated by some script in the repository. Thanks.

**Comment by p-holl** [comment]
Hi kuwt, for the Burgers' experiment, I would recommend checking out the notebook first. The legacy code is not as polished.

The basic shapes are located in [`/notebooks/shapes`](https://github.com/holl-/PDE-Control/tree/master/notebooks/shapes).
You may need to copy them to the right directory before running the script.
