### ISSUE TITLE
Question regarding the CFE chain differentiable loss example for Burger's equation

### ISSUE THREAD

**Issue by kuwt** [holl-/PDE-Control#4]
In this example,  
![image](https://user-images.githubusercontent.com/20258451/117734465-d1cd6400-b1f3-11eb-8996-f269cba10270.png)

I see that the loss is just force loss. I wonder whether the neural network will just ignore the target state input and imitates the natural flow directly.

**Comment by p-holl** [comment]
That's from `burgercfe_diffphys.py`, right?
In the Burgers example, the last force is computed to fit the target state exactly.
This will be very large if the network does not predict any prior forces.

You can see that in line 52: `u_reconstructed = self.u_reconstructed = [u_true[i] if i == 0 or i == n else None for i in range(n+1)]` which fixes the first and last state to the reference.
