### ISSUE TITLE
About smokeik_indirect_training.py: how to generate D.3 incompressible fuild with indirect control?

### ISSUE THREAD

**Issue by XiangZheng2002** [holl-/PDE-Control#6]
I'm trying to generate the data in experiment D.3 incompressible fluid with indirect control. but all I have is a squared density and simple velocity without considering the PDE and fluid dynamic. Could you explain to me how did you generate the data and where is the code? I have been tried a lot to find the code but I failed to find it out. Thanks a lot!!! :)

**Comment by p-holl** [comment]
Hi @Ashleyhoho, the PDE implementations are [here](https://github.com/holl-/PDE-Control/tree/master/src/control/pde).
Then, the PDE object is passed to [ControlTraining](https://github.com/holl-/PDE-Control/blob/master/src/control/control_training.py#L9). 

You can check one of the [example notebooks](https://github.com/holl-/PDE-Control/tree/master/notebooks) which show how everything is put together.

**Comment by XiangZheng2002** [comment]
Thank you for your reply! :) I have a few more questions that I would like to ask you. In the PDE-Control/legacy/apps/smokeik_indirect_training.py file, the SmokeIK class's __init__ method contains references to self.initial_density, self.target_density, and self.true_velocity. I'm curious about the source of these data. Are they generated from the squaregen_buckets_rising.py so the self.initial_density/ self.target_density is the square density fields and self.true_velocity is the velocity making the smoke move in a straight line? Or are they obtained from accurate computations of the flow field by phiflow? Thank you very much!

**Comment by XiangZheng2002** [comment]
I notice that the dataset you generate is the smoke's squared density and the smoke's simple velocity without considering the PDE and fluid dynamic. In the experiment incompressible fluid with indirect control, is it possible for me to generate a sequence where each state has density, velocity and force at each moment directly? [where these force (act in the specified religion in D.3 experiment) make the smoke moving in a predefined trajactory from initial state to end state] Thank you !!!

**Comment by XiangZheng2002** [comment]
Also, I wanna inquire whether the indirectly controlled data is predetermined, such as setting the trajectory of smoke motion and then inferring the flow field information, or if it involves generating random controls and subsequently computing the corresponding flow field and smoke trajectory? Additionally, I wonder if there are existing implementations of the approach mentioned above in available codebases. Thank you!

**Comment by p-holl** [comment]
The initial state and the desired target are randomly generated to create a training and test set.
The full trajectories or controls are not part of the data sets.
During training, the trajectories are unrolled with the network in the loop. This is where the controls are inferred and optimized.
